return {
    "folke/trouble.nvim",
    dependencies = { "kyazdani42/nvim-web-devicons" },
    -- Tells Lazy to require("trouble") and call .setup() with opts below
    main = "trouble",
    opts = {
        position = "bottom",
        height = 10,
        width = 50,
        icons = false,
        mode = "workspace_diagnostics",
        fold_open = "v",
        fold_closed = ">",
        group = true,
        padding = true,
        action_keys = {
            close = "q",
            cancel = "<esc>",
            refresh = "r",
            jump = { "<cr>", "<tab>" },
            open_split = { "<c-x>" },
            open_vsplit = { "<c-v>" },
            open_tab = { "<c-t>" },
            jump_close = { "o" },
            toggle_mode = "m",
            toggle_preview = "P",
            hover = "K",
            preview = "p",
            close_folds = { "zM", "zm" },
            open_folds = { "zR", "zr" },
            toggle_fold = { "zA", "za" },
            previous = "k",
            next = "j",
        },
        indent_lines = false,
        auto_close = true,
        auto_preview = true,
        auto_fold = false,
        auto_jump = { "lsp_definitions" },
        signs = {
            error = "error",
            warning = "warn",
            hint = "hint",
            information = "info",
        },
        use_diagnostic_signs = false,
        opts = {
            modes = {
                diagnostics = {
                    auto_open = true,
                },
            },
        },
    },
}
